#!/bin/bash

echo "Criando diretórios"

mkdir /publico
mkdir /adm
mkdir /ven
mkdir /sec

echo "Diretórios criados.."

echo "Criando grupo de usuários"

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Finalizado."

echo "Criando usuários.."

useradd carlos -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_ADM
useradd maria -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_ADM
useradd joao_ -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_ADM

useradd josefina -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_SEC
useradd amanda -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_SEC
useradd rogerio -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_SEC

useradd debora -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_VEN
useradd sebastiana -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_VEN
useradd roberto -m -s /bin/bash -p $(openssl passwd -crypt eve) -G GRP_VEN

echo "Usuarios criados"

echo "Permissões dos diretórios"

chown root:GRP_ADM /adm
chown root:GRP_SEC /sec
chown root:GRP_VEN /ven

chmod 770 /adm
chmod 770 /sec
chmod 770 /ven
chmod 777 /publico

echo "Todos os processos foram finalizados!"
